name: learning_appfinal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.0.0
  assets_audio_player: ^3.0.3+3
  carousel_slider: ^2.3.1
  cupertino_icons: ^1.0.0
  flare_flutter: ^2.0.6
  flip_card: ^0.5.0
  flutter_swiper: ^1.1.6
  google_fonts: ^2.1.0
  intl: ^0.17.0
  intro_views_flutter: ^3.2.0
  percent_indicator: ^2.1.9
  photo_view: ^0.11.1
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sqflite: ^1.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_app.png"
  adaptive_icon_background: "assets/icon/icon_app.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animaciones/
    - assets/imagenes/
    #- assets/fonts/
    - assets/sonidos_preguntas/
    - assets/database/
    - assets/imagenes_preguntas/
    - assets/imagenes_reading/
    - assets/imgenes_recomen/
    - assets/icon/
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    #fonts:
    #- family: Trajan Pro
    #  fonts:
    #    - asset: fonts/TrajanPro.ttf
    #    - asset: fonts/TrajanPro_Bold.ttf
    #      weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
